# Generated by Django 4.2.6 on 2024-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.URLField()),
                ('word', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('author_lowercase', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
