# Generated by Django 4.2.6 on 2023-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordcount",
            name="author_lowercase",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
